sources:
  - name: source_seed_db
    database: dbt_demo_team_a #"{{ env_var('DBT_SNOWFLAKE_SOURCE_DB') }}"
    schema: dbt_demo_team_a_bronze_db
    #freshness: # default freshness
    #  warn_after: { count: 12, period: hour }
    #  error_after: { count: 24, period: hour }
    #  loaded_at_field: _etl_loaded_at

    tables:
      - name: CrossFit_Games_Athletes_Men_2019
      - name: CrossFit_Games_Athletes_Women_2019
      - name: CrossFit_Games_Scores_2019
      - name: Country_Metadata
