
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_with_datavault_demo'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_with_datavault_demo'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  dbt_with_datavault_demo:
    # Config indicated by + and applies to all files under models/example/
    # to be removed
    example:
      +materialized: view
      +enabled: false
    #
    l_00_brz:
      schema: 'bronze_db'
      materialized: view
      +tags:
        - 'medallion_bronze'
        - 'raw'
      +enabled: true
    l_10_stg:
      schema: 'data_vault'
      +materialized: view
      +tags:
        - 'medallion_bronze'
        - 'stage'
      +enabled: true
    l_20_data_vault:
      schema: 'data_vault'
      +materialized: table
      +tags:
        - 'medallion_silver'
        - 'data_vault'
      +enabled: true
    l_30_data_marts:
      schema: 'data_marts'
      +materialized: table
      +tags:
        - 'medallion_gold'
        - 'marts'
      +enabled: true


seeds:
  dbt_with_datavault_demo:
    meta:
      +schema: 'bronze_db'
      +quote_columns: true
      +delimiter: ','
    data:
      +schema: 'bronze_db'
      +quote_columns: true
      +delimiter: ';'