version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
sources:
  - name: source_seed_db

    tables:
      - name: Countries
        meta:
          contains_pii: false
        columns:
          - name: country
            description: Country name
            meta:
              contains_pii: false
          - name: population
            description: Population
            meta:
              contains_pii: false
          - name: source
            description: Source the population was obtained from
            meta:
              contains_pii: false